### ISSUE TITLE
Password contains $ is regarded as escape character in Linux

### ISSUE THREAD

**Issue by shawncx** [Azure-Samples/djangoapp#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Deploy demo into app service with Linux, Python 3.7.7
> 2. Set pwd in Application settings. The pwd contains $, like 123$123
> 3. SSH to app service and run python manage.py migrate

### Any log messages given by the failure
> django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
FATAL:  password authentication failed for user "xxx"

### Expected/desired behavior
> Should connect with DB successfully

### OS and Version?
> PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
> NAME="Debian GNU/Linux"
> VERSION_ID="9"

### Versions
>

### Mention any other details that might be useful
> App itself can connect with db successfully. It seems caused by migrate command. If you try print variable from console, the following character will be escaped too.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by shizn** [comment]
Adding more info after digging into this issue. 
On my WSL2 (I assume the same behavior on linux/mac?), If run `az postgres up` command with `$` in the password, characters after `$` will be escaped during provision. 
![image](https://user-images.githubusercontent.com/3619378/96308522-67837680-0fb8-11eb-9cb3-a13160c0f08b.png)
This issue is more client issue, tracking it here https://github.com/Azure/azure-cli/issues/15274. Nothing need to be resolved in this sample app.

On my Win10 cmd, run `az postgres up` command with `$` in the password, provisioning is just fine.
![image](https://user-images.githubusercontent.com/3619378/96308707-b7fad400-0fb8-11eb-860b-2cc285d9a02f.png) After updated the webapp appsettings and run django migrate in the web SSH. 
![image](https://user-images.githubusercontent.com/3619378/96309271-d7463100-0fb9-11eb-89c3-d56765c9883b.png)
From the WebApp Linux env, I got this,
![image](https://user-images.githubusercontent.com/3619378/96309881-0c06b800-0fbb-11eb-9047-f3d61f346478.png)
While this is what I got from the portal,
![image](https://user-images.githubusercontent.com/3619378/96310006-4ec89000-0fbb-11eb-94b5-6de4d5a7854f.png)

This issue is out of control of this sample app. Probably this is an issue in Azure App Service.

**Comment by kraigb** [comment]
Not an issue with the sample code itself, but with the behavior of the underlying services. Notes have been made in documentation related to this sample, so closing.
